/**:
  ros__parameters:
    'debug': False
    'compute_brightness': False
    'adjust_timestamp': True
    'dump_node_map': False
    # set parameters defined in blackfly_s.yaml
    'gain_auto': 'Continuous'
    # 'pixel_format': 'BayerRG8'
    'exposure_auto': 'Continuous'
    # These are useful for GigE cameras
    # 'device_link_throughput_limit': 380000000
    # 'gev_scps_packet_size': 9000
    # ---- to reduce the sensor width and shift the crop
    'image_width': 720
    'image_height': 540
    # 'offset_x': 16
    # 'offset_y': 0
    'binning_x': 2
    'binning_y': 2
    # 'connect_while_subscribed': True
    'frame_rate_auto': 'Off'
    'frame_rate': 40.0
    'frame_rate_enable': True
    'buffer_queue_size': 10
    'trigger_mode': 'Off'
    'chunk_mode_active': True
    'chunk_selector_frame_id': 'FrameID'
    'chunk_enable_frame_id': True
    'chunk_selector_exposure_time': 'ExposureTime'
    'chunk_enable_exposure_time': True
    'chunk_selector_gain': 'Gain'
    'chunk_enable_gain': True
    'chunk_selector_timestamp': 'Timestamp'
    'chunk_enable_timestamp': True
